export const enum UI_DEPTHS {
	BASE_TILE_LAYER = 0,
	DECORATION_TILE_LAYER= 1,

	TOKEN_BACKGROUND_LAYER = 2,
	TOKEN_MAIN_LAYER = 3,
	TOKEN_FOREGROUND_LAYER = 4,

	OVERLAY_TILE_LAYER = 5,
	OVERLAY_DECORATION_TILE_LAYER = 6,

	UI_BACKGROUND_LAYER = 7,
	UI_MAIN_LAYER = 8,
	UI_FOREGROUND_LAYER = 9
}