import AbilityEffect from '../drawables/effects/AbilityEffect';
import FireBallEffect from '../drawables/effects/FireBallEffect';
import IceSpikeEffect from '../drawables/effects/IceSpikeEffect';
import DustNovaEffect from '../drawables/effects/DustNovaEffect';
import RoundHouseKickEffect from '../drawables/effects/RoundHouseKickEffect';
import HealingLightEffect from '../drawables/effects/HealingLightEffect';
import ArcaneBoltEffect from '../drawables/effects/ArcaneBoltEffect';
import ConeEffect from '../drawables/effects/ConeEffect';
import NecroticBoltEffect from '../drawables/effects/NecroticBoltEffect';

export type SpreadData = [number, number, ((factor: number) => number)?];

export interface ProjectileData {
	spread?: SpreadData;
	velocity: number;
	drag?: number;
	effectScale?: number;
	spriteScale?: number;
	xOffset: number;
	yOffset: number;
	effect: typeof AbilityEffect;
	collisionSound?: string;
	sfxVolume?: number;
	delay?: number;
	targeting?: boolean;
	knockback?: number;
	timeToLive?: number;
	destroyOnEnemyContact: boolean;
	destroyOnWallContact: boolean;
	explodeOnDestruction?: boolean;
	passThroughEnemies?: boolean;
	shape?: 'source' | 'storm' | 'cone' | 'nova';
}

interface AbilityData {
	projectiles?: number;
	projectileData?: ProjectileData;
	sound?: string;
	sfxVolume?: number;
	cooldownMs?: number;
	flavorText?: string;
	icon?: [string, number];
	damageMultiplier: number;
	stun?: number;
}

export const enum AbilityType {
	NOTHING = 'nothing',
	FIREBALL = 'fireball',
	ARCANE_BOLT = 'arcaneBolt',
	HAIL_OF_BOLTS = 'hailOfBolts',
	HAIL_OF_FLAMES = 'hailOfFlames',
	HAIL_OF_ICE = 'hailOfIce',
	ICESPIKE = 'icespike',
	DUSTNOVA = 'dustnova',
	ROUND_HOUSE_KICK = 'roundhousekick',
	HEALING_LIGHT = 'healinglight',
	ARCANE_BLADE = 'arcaneBlade',
	FIRE_CONE = 'fireCone',
	FIRE_NOVA = 'fireNova',
	ARCANE_CONE = 'arcaneCone',
	ARCANE_NOVA = 'arcaneNova',
	ICE_CONE = 'iceCone',
	ICE_NOVA = 'iceNova',
	NECROTIC_BOLT = 'nectoricBolt',
}

export const Abilities: { [type: string]: AbilityData } = {
	[AbilityType.NOTHING]: {
		projectiles: 0,
		cooldownMs: 0,
		damageMultiplier: 0,
		flavorText: ``,
		icon: ['icon-abilities', 2],
	},
	[AbilityType.FIREBALL]: {
		projectiles: 1,
		projectileData: {
			velocity: 300,
			xOffset: 0,
			yOffset: 0,
			effect: FireBallEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 250,
		damageMultiplier: 1,
		stun: 3000,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
	[AbilityType.ARCANE_BOLT]: {
		projectiles: 1,
		projectileData: {
			velocity: 450,
			xOffset: 0,
			yOffset: 0,
			effect: ArcaneBoltEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			knockback: 120,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 250,
		damageMultiplier: 0.8,
		flavorText: `Shooting magic missiles!`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.HAIL_OF_BOLTS]: {
		projectiles: 13,
		projectileData: {
			spread: [-0.07, 0.07, (num) => Math.sin(num * Math.PI * 0.95)],
			velocity: 350,
			delay: 50,
			xOffset: 0,
			yOffset: 0,
			effect: ArcaneBoltEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			targeting: true,
			knockback: 200,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 3000,
		damageMultiplier: 0.25,
		flavorText: `Shooting magic missiles!`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.HAIL_OF_FLAMES]: {
		projectiles: 13,
		projectileData: {
			spread: [-0.07, 0.07, (num) => Math.sin(num * Math.PI * 0.95)],
			delay: 50,
			velocity: 350,
			effectScale: 0.8,
			xOffset: 0,
			yOffset: 0,
			effect: FireBallEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			targeting: true,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 3000,
		damageMultiplier: 0.33,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
	[AbilityType.HAIL_OF_ICE]: {
		projectiles: 13,
		projectileData: {
			spread: [-0.07, 0.07, (num) => Math.sin(num * Math.PI * 0.95)],
			delay: 50,
			velocity: 350,
			spriteScale: 0.5,
			effectScale: 0.5,
			xOffset: 0,
			yOffset: 0,
			effect: IceSpikeEffect,
			collisionSound: 'sound-icespike-hit',
			sfxVolume: 0.2,
			targeting: true,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-icespike',
		sfxVolume: 0.3,
		cooldownMs: 3000,
		damageMultiplier: 0.25,
		flavorText: `A pointy icespike. Although it is generally used to impale the caster's adversaries, it has many alternative uses. Such as cooling drinks... or cooling anything, really.`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.ICESPIKE]: {
		projectiles: 1,
		projectileData: {
			velocity: 400,
			xOffset: 16,
			yOffset: 16,
			effect: IceSpikeEffect,
			collisionSound: 'sound-icespike-hit',
			sfxVolume: 0.2,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-icespike',
		sfxVolume: 0.3,
		cooldownMs: 400,
		damageMultiplier: 0.8,
		flavorText: `A pointy icespike. Although it is generally used to impale the caster's adversaries, it has many alternative uses. Such as cooling drinks... or cooling anything, really.`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.DUSTNOVA]: {
		projectiles: 32,
		projectileData: {
			spread: [-1, 1],
			velocity: 150,
			// drag: 200,
			xOffset: 20,
			yOffset: 20,
			effect: DustNovaEffect,
			destroyOnWallContact: true,
			destroyOnEnemyContact: true,
			// collisionSound: 'sound-wind',
			// sfxVolume: 0.4
		},
		sound: 'sound-wind',
		sfxVolume: 1.4,
		cooldownMs: 1200,
		damageMultiplier: 0.05,
		icon: ['icon-abilities', 2],
	},
	[AbilityType.ROUND_HOUSE_KICK]: {
		projectiles: 16,
		projectileData: {
			// tslint:disable-next-line: no-magic-numbers
			spread: [-0.4, 0.4],
			velocity: 50,
			xOffset: 25,
			yOffset: 25,
			effect: RoundHouseKickEffect,
			delay: 12,
			destroyOnWallContact: true,
			destroyOnEnemyContact: true,
			// collisionSound: 'sound-wind',
			// sfxVolume: 0.4
		},
		sound: 'sound-wind',
		sfxVolume: 1.4,
		cooldownMs: 1200,
		damageMultiplier: 0.1,
		icon: ['icon-abilities', 2],
	},
	[AbilityType.HEALING_LIGHT]: {
		projectiles: 1,
		projectileData: {
			velocity: 0,
			xOffset: 0,
			yOffset: 0,
			effect: HealingLightEffect,
			destroyOnWallContact: true,
			destroyOnEnemyContact: false,
			// collisionSound: 'sound-wind',
			// sfxVolume: 0.4
		},
		sound: 'sound-wind',
		sfxVolume: 1.4,
		cooldownMs: 1200,
		damageMultiplier: 1,
		icon: ['icon-abilities', 2],
	},
	[AbilityType.ARCANE_BLADE]: {
		projectiles: 50,
		projectileData: {
			spread: [-0.2, 0.2],
			velocity: 200,
			xOffset: 32,
			yOffset: 32,
			effect: ArcaneBoltEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			destroyOnWallContact: true,
			destroyOnEnemyContact: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 400,
		damageMultiplier: 0.2,
		flavorText: `A blade of arcane power.`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.FIRE_CONE]: {
		projectiles: 12,
		projectileData: {
			spread: [-0.14, 0.14],
			velocity: 400,
			drag: 700,
			xOffset: 0,
			yOffset: 0,
			effect: FireBallEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			timeToLive: 500,
			effectScale: 1.2,
			targeting: false,
			destroyOnWallContact: false,
			destroyOnEnemyContact: false,
			explodeOnDestruction: false,
			passThroughEnemies: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 1500,
		damageMultiplier: 0.2,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
	[AbilityType.ARCANE_CONE]: {
		projectiles: 12,
		projectileData: {
			spread: [-0.14, 0.14],
			velocity: 400,
			drag: 700,
			xOffset: 0,
			yOffset: 0,
			effect: ArcaneBoltEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			timeToLive: 500,
			effectScale: 1.2,
			targeting: false,
			destroyOnWallContact: false,
			destroyOnEnemyContact: false,
			explodeOnDestruction: false,
			passThroughEnemies: true,
			knockback: 100,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 1500,
		damageMultiplier: 0.15,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
	[AbilityType.ICE_CONE]: {
		projectiles: 12,
		projectileData: {
			spread: [-0.14, 0.14],
			velocity: 400,
			drag: 700,
			xOffset: 0,
			yOffset: 0,
			effect: IceSpikeEffect,
			collisionSound: 'sound-icespike-hit',
			sfxVolume: 0.2,
			timeToLive: 500,
			spriteScale: 0.5,
			targeting: false,
			destroyOnWallContact: false,
			destroyOnEnemyContact: false,
			explodeOnDestruction: false,
			passThroughEnemies: true,
			knockback: 100,
			shape: 'cone',
		},
		sound: 'sound-icespike',
		sfxVolume: 0.1,
		cooldownMs: 1500,
		damageMultiplier: 0.15,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.ICE_NOVA]: {
		projectiles: 36,
		projectileData: {
			spread: [-1, 1],
			velocity: 300,
			drag: 700,
			xOffset: 0,
			yOffset: 0,
			effect: IceSpikeEffect,
			collisionSound: 'sound-icespike-hit',
			sfxVolume: 0.2,
			timeToLive: 500,
			spriteScale: 0.7,
			effectScale: 0.7,
			targeting: false,
			destroyOnWallContact: false,
			destroyOnEnemyContact: false,
			explodeOnDestruction: false,
			passThroughEnemies: true,
			shape: 'nova',
		},
		sound: 'sound-icespike',
		sfxVolume: 0.1,
		cooldownMs: 1500,
		damageMultiplier: 0.15,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 1],
	},
	[AbilityType.FIRE_NOVA]: {
		projectiles: 36,
		projectileData: {
			spread: [-1, 1],
			velocity: 300,
			drag: 700,
			xOffset: 0,
			yOffset: 0,
			effect: FireBallEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			timeToLive: 500,
			effectScale: 1.2,
			targeting: false,
			destroyOnWallContact: false,
			destroyOnEnemyContact: false,
			explodeOnDestruction: false,
			passThroughEnemies: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 1500,
		damageMultiplier: 0.25,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
	[AbilityType.ARCANE_NOVA]: {
		projectiles: 36,
		projectileData: {
			spread: [-1, 1],
			velocity: 300,
			drag: 700,
			xOffset: 0,
			yOffset: 0,
			effect: ArcaneBoltEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			timeToLive: 500,
			effectScale: 1.2,
			targeting: false,
			destroyOnWallContact: false,
			destroyOnEnemyContact: false,
			explodeOnDestruction: false,
			passThroughEnemies: true,
			knockback: 100,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 1500,
		damageMultiplier: 0.15,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
	[AbilityType.NECROTIC_BOLT]: {
		projectiles: 1,
		projectileData: {
			velocity: 300,
			xOffset: 0,
			yOffset: 0,
			effect: NecroticBoltEffect,
			collisionSound: 'sound-fireball-explosion',
			sfxVolume: 0.2,
			destroyOnEnemyContact: true,
			destroyOnWallContact: true,
			explodeOnDestruction: true,
		},
		sound: 'sound-fireball',
		sfxVolume: 0.1,
		cooldownMs: 250,
		damageMultiplier: 1,
		stun: 3000,
		flavorText: `A big ol' fireball. A classic in every Mage's arsenal, it is typically used to incinerate your enemies. More advanced mages can control it enough to boil water, or cook food!`,
		icon: ['icon-abilities', 0],
	},
};
